local utils = require("rekt.utils")

describe("utils", function()
	it("can rewrite the file name with test suffix", function()
		assert.equal("somefilename_test.go", utils.make_test_name("somefilename.go"))
		assert.equal("somefilename.spec.ts", utils.make_test_name("somefilename.ts"))
		assert.equal("somefilename.spec.tsx", utils.make_test_name("somefilename.tsx"))
		assert.equal("some.file.name.spec.js", utils.make_test_name("some.file.name.js"))
	end)

	it("can rewrite the file name without test suffix", function()
		assert.equal("somefilename.go", utils.make_source_name("somefilename_test.go"))
		assert.equal("somefilename.ts", utils.make_source_name("somefilename.spec.ts"))
		assert.equal("somefilename.tsx", utils.make_source_name("somefilename.spec.tsx"))
		assert.equal("some.file.name.js", utils.make_source_name("some.file.name.spec.js"))
	end)
end)
